In [1]:
# Required Python packages
from datetime import date, datetime, timedelta
import calendar
import pandas as pd
import numpy as np
import itertools
import copy
from numpy.linalg import multi_dot
from scipy.stats import norm
from scipy.stats import bernoulli
from scipy.special import roots_hermite
from scipy.optimize import fmin_slsqp as min

import matplotlib.pyplot as plt
import math
import pickle

from scipy.interpolate import CubicSpline

#Import Date opertative user defined functions
from ipynb.fs.full.user_defined_vik_functions import get_all_monthly_option_expiries, \
                                                     find_last_thurs_date_of_month, \
                                                     prev_workday_if_holiday, find_wkly_expries,\
                                                     date_of_prev_thurs

# Import dataframe naming functions 
from ipynb.fs.full.user_defined_vik_functions import get_mthly_df_name_from_expiry

#Import data loading functions
from ipynb.fs.full.user_defined_vik_functions import load_all_mthly_data

#import traded options parameters and info
from ipynb.fs.full.user_defined_vik_functions import generate_weekly_CarrWu_strikes, generate_mthly_strikes

# #Import pricing functions
# from ipynb.fs.full.user_defined_vik_functions import BSM_call_vec, BSM_put_vec

#Import implied volatility processing functions
from ipynb.fs.full.user_defined_vik_functions import generate_weekly_iv, gen_interpolated_iv

#Import Risk-free interest rate generation functions
from ipynb.fs.full.user_defined_vik_functions import generate_weekly_ir

#Import Stochatic process simulation functions
from ipynb.fs.full.user_defined_vik_functions import gamma_with_spot

# Import risk free interest rate function
from ipynb.fs.full.user_defined_vik_functions import get_risk_free_rate_from_exact_date


In [22]:
# Stock Index of Interest
# stock_ident = "BANKNIFTY"
stock_ident = "NIFTY"

# The scope of this code is to hedge one option 
# and scope will be extended to a portfolio
no_of_assets = 1
cor_mat = [[1]]

#Path to refer data
source_path = "/home/jupyter-partha/Vikranth - Chapter 2/"
input_sub_path = "Input Data/mkt_data_covid_region/"
output_sub_path = "Output Data/"
input_data_path = source_path + input_sub_path
output_data_path = source_path + output_sub_path

#Static hedging performed at different moneyness regions 
#i.e. moneyness is used to select the option with nearest moneyness match
# ATM - At the Money, ITM - In the money, OTM - Out of the Money
prod_moneyness = "OTM"

#Product type to hedge: either "CE" or "PE"
# prod_type = "CE"
prod_type = "PE"

# Periods of interest will be a dictionary
#Key is the year, value is a list of months 1-12, 1- Jan, 2 - Feb,...12 - Dec
# For E.g., periods_of_interest = {2020: [3], 2019: [11, 12]}
periods_of_interest = {2019:[8, 9, 10, 11, 12], 2020: [1, 2, 3, 4, 5, 6, 7]}


#List of holidays
holidays_list = [date(2019, 3, 4), date(2019, 3, 21),\
                 date(2019, 4, 17), date(2019, 4, 19), date(2019, 4, 29),\
                 date(2019, 5, 1),\
                 date(2019, 6, 5),\
                 date(2019, 8, 12), date(2019, 8, 15),\
                 date(2019, 9, 2), date(2019, 9, 10), \
                 date(2019, 10, 2), date(2019, 10, 8), date(2019, 10, 21), date(2019, 10, 28), \
                 date(2019, 11, 12), \
                 date(2019, 12, 25), \
                 date(2020, 2, 21), \
                 date(2020, 3, 10), \
                 date(2020, 4, 2), date(2020, 4, 6), date(2020, 4, 10), date(2020,4, 14), \
                 date(2020, 5, 1), date(2020, 5, 25), \
                 date(2020, 10, 2), date(2020, 11, 16), date(2020, 11, 30), date(2020, 12, 25)]

#Simulation Parameters
no_of_paths = 5000

#Number of options
no_opt=1



In [23]:
# def Hermitetuple(no_of_options):
#     return pd.DataFrame(roots_hermite(no_of_options)).transpose()

# def findStrikes(x):
#     return K*np.exp(x*sigma*np.sqrt(2*(T-t))+(delta-r-(sigma**2)/2)*(T-t))

# def findWeights(x):
#     return (np.exp(-delta*(T-t))/np.sqrt(np.pi))*x   

# def portfolioStrikes(no_of_options):
#     return pd.Series(Hermitetuple(no_of_options)[0].apply(findStrikes))

# def portfolioWeights(no_of_options):
#     return pd.Series(Hermitetuple(no_of_options)[1].apply(findWeights))

def generate_CarrWu_avail_Strikes(aa, bb):
    aa_nearest = np.array(bb[abs(aa[None, :] - bb[:, None]).argmin(axis=0)])
    
    if (len(np.unique(aa_nearest)) < len(aa_nearest)):
        print("There are repititions in the CarrWu strikes")
        
    return aa_nearest


In [24]:
#########################
#User-defined functions #
#########################

def Hermitetuple(no_of_options):
    return pd.DataFrame(roots_hermite(no_of_options)).transpose()

def generate_weekly_static_pfl_weights(no_of_paths, mthly_expiries_list, \
                                       dict_wkly_expiries_each_month, \
                                       dict_ce_wkly_strikes, dict_pe_wkly_strikes, \
                                       dict_wkly_spots, dict_wkly_iv, \
                                       prod_type, prod_moneyness, output_path, \
                                       option_type = "CE", no_of_assets=1, cor_mat=[[1]],\
                                       batch_size_divisor=10, no_of_epochs = 1000, stock_ident="BANKNIFTY"):
    ce_pfl_weights = []
    pe_pfl_weights = [] 
    cash_weights = []
    for each_month in mthly_expiries_list:
        strike = dict_mthly_strikes[each_month.strftime("%d-%b-%Y")]
        weekly_pfl_weights = []
        ce_dict = {}
        pe_dict = {}
        cash_dict = {}
        week_list = dict_wkly_expiries_each_month[each_month.strftime("%d-%b-%Y")]
        no_of_weeks = len(week_list)
        
        for week in range(0, no_of_weeks):
            s_t = dict_wkly_spots[each_month.strftime("%d-%b-%Y")][week] 
            K = strike
            r = np.array([dict_wkly_ir[each_month.strftime("%d-%b-%Y")][week]])[0]
            
            if (week == no_of_weeks-1):
                sim_start_date = dict_wkly_expiries_each_month[each_month.strftime("%d-%b-%Y")][week]
                sim_end_date = each_month
            else:
                sim_start_date = dict_wkly_expiries_each_month[each_month.strftime("%d-%b-%Y")][week]
                sim_end_date = dict_wkly_expiries_each_month[each_month.strftime("%d-%b-%Y")][week + 1]
              
            df_full_iv = pd.read_csv(output_path + "A3_" + stock_ident + "_implied_vol_surface.csv")
            df_date = df_full_iv[df_full_iv['Date'] == sim_start_date.strftime("%d-%b-%Y")]
            
            # We define Moneyness as (S/K) in vol surface for both calls and puts
            option_moneyness = float(s_t/float(K))
            
            # Vol Surface is already sorted when created in code A3 - This is just to make sure again
            df_date = df_date.sort_values(['T', 'Moneyness'], ascending=[False, True]).reset_index()
            
            # np.unique also sorts the array - we need to re-sort in descending order
            # This is required as last week has only one tenor and when filtering, we need to filter as 
            # tenor_list[0]
            
#             t_list = -np.sort(np.unique(np.array(-df_date['T'])))
# Changed the sorting to get the vol as of 1 week as thats what needed for simulation - bug in previous step resolved

# BUT FOR CARRWU - again changed to longer tenor as it has no simulation and takes th full vol 

            # Need higher tenor first
            t_list = -np.sort(np.unique(np.array(-df_date['T'])))
            tenor_list = [str(int(round(t* 365))) + "D" for t in t_list]
            print(each_month, " Week: ", week)
            print(tenor_list)
            
            if (len(tenor_list) > 2):
                print("There are more than 2 tenors in the vol surface - Please check!")
                
            df_tenor = df_date[df_date['Tenor'] == tenor_list[0]]

            x = np.array(df_tenor["Moneyness"])
            y = np.array(df_tenor["Impl_Vol"])
            cubic_spline = CubicSpline(x, y, bc_type='natural')
            x_min = np.amin(x)
            x_max = np.amax(x)
            
            if (option_moneyness <= x_min):
                vol_list = [cubic_spline(x_min)]
            elif (option_moneyness >= x_max):
                vol_list = [cubic_spline(x_max)]
            else:
                vol_list = [cubic_spline(option_moneyness)]
            
            vol = vol_list[0]
            dt = float((each_month - sim_end_date).days) / 365
    
            # r =risk_free rate - divid -> as obtained from futures: r = rf - q
#             risk_free_rate = 0.05
            risk_free_rate = get_risk_free_rate_from_exact_date(sim_start_date)

            #dividend
            q = risk_free_rate - r
            
            #Gaussian Quadrature - Strikes and weights   
            find_strikes = lambda x:  K*np.exp(x*vol*np.sqrt(2*(dt))+(-r-(vol**2)/2)*(dt))
            find_weight = lambda x: (np.exp(-q*(dt))/np.sqrt(np.pi))*x 
            generate_hermite_table = lambda no_of_calls: pd.DataFrame(roots_hermite(no_of_calls)).transpose()
            
            #Generate theoretical strikes and weights
            no_of_calls=10
            hermit_table = generate_hermite_table(no_of_calls=no_of_calls)
            call_theoritical_strikes = np.array(pd.Series(hermit_table[0].apply(find_strikes)))
            ce_wt_list = pd.Series(hermit_table[1].apply(find_weight))
            
            ce_dates_list = np.array([sim_start_date.strftime("%d-%b-%Y") for i in range(0, no_of_calls)]).reshape(-1)
            
#             if (week == no_of_weeks-1):
#                 call_theoritical_strikes = np.array([call_theoritical_strikes[0]])
#                 ce_dates_list = [ce_dates_list[0]]
#                 ce_wt_list = [ce_wt_list[0]]
                
            print("Theoeretical Strikes: ")
            print(call_theoritical_strikes)  
            call_available_strikes = np.sort(np.array(dict_ce_wkly_strikes[each_month.strftime("%d-%b-%Y")][week])).reshape(-1)
            print("Market Liquid Available Strikes: ")
            print(call_available_strikes)
            call_strikes = generate_CarrWu_avail_Strikes(call_theoritical_strikes, call_available_strikes)
            print("Final CarrWu Strikes: ")
            print(call_strikes)
            ce_dict = {"Date": ce_dates_list, "Strike": call_strikes, "Pfl_weights": ce_wt_list}
            df_ce = pd.DataFrame(ce_dict)
            df_ce = df_ce.groupby(['Date', 'Strike'])[['Pfl_weights']].sum().reset_index()
        
            ce_pfl_weights.append(df_ce)
 
            # Put options
            put_strikes = [0]
            pe_wt_list = [0]

            #Put Pfl Weights
            pe_dates_list = np.array([sim_start_date.strftime("%d-%b-%Y") for i in range(0, 1)]).reshape(-1)
            pe_dict = {"Date": pe_dates_list, "Strike":put_strikes, "Pfl_weights": pe_wt_list}
            df_pe = pd.DataFrame(pe_dict)
            pe_pfl_weights.append(df_pe)
            
            # Cash component
            cash_date = [sim_start_date.strftime("%d-%b-%Y")]
            cash_dict = {"Date":cash_date, "Pfl_weights":[0]} 
            df_cash = pd.DataFrame(cash_dict)
            cash_weights.append(df_cash)
                   
        df_ce_pfl_weights = pd.concat(ce_pfl_weights, axis=0)
        df_pe_pfl_weights = pd.concat(pe_pfl_weights, axis=0)
        df_cash_pfl_weights = pd.concat(cash_weights, axis=0)

        df_ce_pfl_weights.to_csv(output_path  + "B0A_" + stock_ident + "_" + prod_moneyness + "_" + prod_type + "_CE_Pfl_weights.csv", index = False)
        df_pe_pfl_weights.to_csv(output_path + "B0A_" + stock_ident + "_" + prod_moneyness + "_" + prod_type + "_PE_Pfl_weights.csv", index = False)
        df_cash_pfl_weights.to_csv(output_path  + "B0A_" + stock_ident + "_" + prod_moneyness + "_" + prod_type + "_Cash_Pfl_weights.csv", index = False)
    
    return df_ce_pfl_weights, df_pe_pfl_weights, df_cash_pfl_weights

def output_strikes_hedged(prod_type, prod_moneyness, dict_mthly_strikes, stock_ident, output_path):
    list_of_dates = []
    list_of_prod_type = []
    list_of_strikes = []
    for each_month in dict_mthly_strikes.keys():
        list_of_dates.append(each_month)
        list_of_strikes.append(dict_mthly_strikes[each_month])
        list_of_prod_type.append(prod_type)
    dict_hedged_prod = {"Date":list_of_dates, "prod_type":list_of_prod_type, "Strike":list_of_strikes}
    df_hedged_prod = pd.DataFrame(dict_hedged_prod) 
    df_hedged_prod.to_csv(output_path + "B0A_" + stock_ident + "_" + prod_moneyness + "_" + prod_type + "_strikes_hedged.csv", index = False)
    return(df_hedged_prod)


In [25]:

#Find the monthly strikes of option from mkt data to find the option to be hedged
#Every month, an option is hedged
mthly_expiries_list = get_all_monthly_option_expiries(periods_of_interest, holidays_list)
dict_wkly_expiries_each_month = find_wkly_expries(mthly_expiries_list, holidays_list)

# #Load all monthly mkt data
mthly_mkt_data = load_all_mthly_data(mthly_expiries_list, input_data_path, holidays_list, prod_type_lists=["FUT", "CE", "PE"], stock_ident=stock_ident)

# #Load weekly strikes of short term options used for hedging monthly options 
dict_ce_wkly_strikes, dict_pe_wkly_strikes, dict_wkly_spots = generate_weekly_CarrWu_strikes(dict_wkly_expiries_each_month, input_data_path, stock_ident = stock_ident)     

#Load monthly strikes of interest as of required moneyness on the begining of month
dict_mthly_strikes = generate_mthly_strikes(mthly_mkt_data, prod_moneyness, prod_type, holidays_list, stock_ident=stock_ident)

#Load weekly IV for Black-Scholes model input and monte-carlo simulation of stock paths
dict_wkly_iv = generate_weekly_iv(dict_wkly_expiries_each_month, dict_wkly_spots, dict_mthly_strikes, prod_type, output_path=output_data_path, atm_ind=0, stock_ident=stock_ident)

#Load weekly risk free interest rates from futures
#This function to be changed based on updates on risk-free-interest - now kept it as cosntant
dict_wkly_ir = generate_weekly_ir(dict_wkly_expiries_each_month, mthly_mkt_data, stock_ident)

# #Load Static portfolio weights built by neural network
ce_pfl_wts, pe_pfl_wts, cash_pfl_wts = generate_weekly_static_pfl_weights(no_of_paths, mthly_expiries_list, dict_wkly_expiries_each_month, \
                                                        dict_ce_wkly_strikes, dict_pe_wkly_strikes, dict_wkly_spots, \
                                                        dict_wkly_iv, prod_type, prod_moneyness, output_data_path, \
                                                        option_type = prod_type, no_of_assets=no_of_assets, \
                                                        cor_mat=cor_mat, stock_ident=stock_ident) 

# The strike correspnding to the option that is hedged
df_hedged_prod = output_strikes_hedged(prod_type, prod_moneyness, dict_mthly_strikes, stock_ident, output_data_path)



2019-08-29  Week:  0
['35D', '7D']
Theoeretical Strikes: 
[ 7724.79355578  8256.80734816  8742.97187933  9219.63735637
  9703.41297368 10206.62211241 10742.18709423 11327.84947612
 11994.83834936 12820.9341399 ]
Market Liquid Available Strikes: 
[11200 11250 11300 11350 11400 11450 11500 11550 11600 11650 11700 11800
 11900 12000 12500]
There are repititions in the CarrWu strikes
Final CarrWu Strikes: 
[11200 11200 11200 11200 11200 11200 11200 11350 12000 12500]
2019-08-29  Week:  1
['28D', '7D']
Theoeretical Strikes: 
[ 7934.9281071   8424.69531904  8869.47555919  9303.15074395
  9740.9907369  10194.0920547  10673.86297492 11195.76412532
 11786.84243352 12514.3611808 ]
Market Liquid Available Strikes: 
[11000 11050 11100 11150 11200 11250 11300 11350 11400 11500 11700]
There are repititions in the CarrWu strikes
Final CarrWu Strikes: 
[11000 11000 11000 11000 11000 11000 11000 11200 11700 11700]
2019-08-29  Week:  2
['21D', '6D']
Theoeretical Strikes: 
[ 7943.52847158  8432.269377   

2019-12-26  Week:  2
['14D', '7D']
Theoeretical Strikes: 
[ 9322.61740969  9706.43152227 10048.7221643  10377.11090283
 10703.62211612 11036.50913483 11383.76802238 11755.78559432
 12170.34530036 12671.40096702]
Market Liquid Available Strikes: 
[11500 11800 11850 11900 11950 12000 12050 12100 12150 12200 12250 12300
 12400 12500 13000]
There are repititions in the CarrWu strikes
Final CarrWu Strikes: 
[11500 11500 11500 11500 11500 11500 11500 11800 12150 12500]
2019-12-26  Week:  3
['7D']
Theoeretical Strikes: 
[10900. 10900. 10900. 10900. 10900. 10900. 10900. 10900. 10900. 10900.]
Market Liquid Available Strikes: 
[10000 10500 11000 11500 11600 11700 11800 11850 11900 12000 12050 12100
 12150 12200 12250 12300 12350 12400 12450 12500 12550 12600 12650 12700
 12800 12900 13000 13500 14000]
There are repititions in the CarrWu strikes
Final CarrWu Strikes: 
[11000 11000 11000 11000 11000 11000 11000 11000 11000 11000]
2020-01-30  Week:  0
['35D', '7D']
Theoeretical Strikes: 
[ 8734.917

2020-04-30  Week:  4
['7D']
Theoeretical Strikes: 
[7800. 7800. 7800. 7800. 7800. 7800. 7800. 7800. 7800. 7800.]
Market Liquid Available Strikes: 
[ 7000  7500  8000  8200  8500  8700  8800  8900  9000  9100  9200  9250
  9300  9350  9400  9500  9600  9700  9750  9800  9900 10000 10100 10200
 10300 10400 10500 10600 10700 10800 11000 11100 11500 12000 12500 13000
 13500]
There are repititions in the CarrWu strikes
Final CarrWu Strikes: 
[8000 8000 8000 8000 8000 8000 8000 8000 8000 8000]
2020-05-28  Week:  0
['28D', '7D']
Theoeretical Strikes: 
[ 5716.97715409  6419.31312639  7091.13024429  7777.22154998
  8500.90196773  9282.50353023 10146.25236255 11127.93726912
 12292.5383093  13802.68809875]
Market Liquid Available Strikes: 
[ 9300  9400  9500  9600  9700  9800  9850  9900  9950 10000 10050 10100
 10200 10300 10400 10500 10550 10600 10700 11000 12000]
There are repititions in the CarrWu strikes
Final CarrWu Strikes: 
[ 9300  9300  9300  9300  9300  9300 10100 11000 12000 12000]
202

In [1]:
# aa = np.array([1.2, 5.6, 10.2, 15.4])
# bb = np.array([2, 5, 12, 19, 20])
# aa_nearest = bb[abs(aa[None, :] - bb[:, None]).argmin(axis=0)]
# print(aa_nearest)


In [48]:
# 26000, 26500 -> 27000 -- 3000
# # print(gamma_with_spot(100, 100, 0.05, 0.5, 1))

In [ ]:
# generate_mthly_strikes(mthly_mkt_data, prod_moneyness, prod_type, holidays_list, stock_ident="BANKNIFTY")